### PR TITLE
Replace the CKEditor image toolbar button with FILElink

### LINKED ISSUE #29: Replace the CKEditor image toolbar button with FILElink
Replace the CKEditor image button with FILELink. The editor image button is confusing, people believe they can only add images by URL.

#### Steps to reproduce the behavior

1. Test in https://github.com/joomlatools/textman/issues/473

#### Support tickets

* https://github.com/joomlatools/textman/issues/473

### PR DESCRIPTION
**Pull request by jebbdomingo**
Resolve #29

### CODE REVIEW

File: resources/assets/ckeditor/plugins/filelink/plugin.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+});
+
+function showDialogPlugin(e){
+    e.openDialog('filelink.dlg');
+}
+
+kQuery(document).ready(function($) {
+    CKEDITOR.on("instanceReady", function(e) {
+        // Remove built-in image button
+        $('#cke_21').hide();
```
Comment (jebbdomingo) [inline resources/assets/ckeditor/plugins/filelink/plugin.js]: @johanjanssens We have to hide the image button instead of removing it via config i.e. `'removeButtons'  => 'Image'` as the removeButton configuration also disables the image plugin thereby disabling all images in the editor.

File: resources/assets/ckeditor/plugins/filelink/plugin.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+        var cmd = editor.addCommand('filelink.cmd', {exec:showDialogPlugin});
+
+        CKEDITOR.dialog.addIframe(
+            'filelink.dlg',
+            'File Link',
+            editor.config.fileLinkUploadUrl,
+            800,
+            400,
+            function(){
```
Comment (jebbdomingo) [inline resources/assets/ckeditor/plugins/filelink/plugin.js]: @ercanozkaya Sir, need your assistance here, can you help with closing the modal dialogue (iframe) when clicking `Insert` button from the loaded FILElink view?

image

Comment (ercanozkaya) [reply resources/assets/ckeditor/plugins/filelink/plugin.js]: Hey @jebbdomingo , is there a reason we are opening Ckeditor's modal instead of our own magnificPopup? We have another ticket to use the same modal everywhere.

It's also easy to use like this:
```
kQuery.magnificPopup.open({
                    items: {
                        src: $(this).attr("href"),
                        type: "iframe"
                    },
                    mainClass: "koowa_dialog_modal"
                });
```

Can you try to use this?

File: resources/assets/ckeditor/plugins/filelink/plugin.js (hunk 1 above)
Comment (johanjanssens) [reply resources/assets/ckeditor/plugins/filelink/plugin.js]: @jebbdomingo Oki. No problem at all. Can you look into this in more detail? Seems a little weird we need to hide it?

**Review by johanjanssens — CHANGES_REQUESTED** [review]
See comment from @ercanozkaya  https://github.com/joomlatools/joomlatools-framework-ckeditor/pull/30#discussion_r157704860

File: resources/assets/ckeditor/plugins/iframedialog/plugin.js [hunk 3]
```diff
@@ -0,0 +1,169 @@
+/**
+ * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
```
Comment (johanjanssens) [inline resources/assets/ckeditor/plugins/iframedialog/plugin.js]: @jebbdomingo Please make sure to change copyright docblocks

Comment (jebbdomingo) [reply resources/assets/ckeditor/plugins/iframedialog/plugin.js]: @johanjanssens It's a third-party IFrame Dialog plugin https://ckeditor.com/cke4/addon/iframedialog

Comment (jebbdomingo) [reply resources/assets/ckeditor/plugins/iframedialog/plugin.js]: @johanjanssens I'll be replacing it with magnificPopup anyway

Comment (johanjanssens) [reply resources/assets/ckeditor/plugins/iframedialog/plugin.js]: Oki.

File: resources/assets/ckeditor/plugins/filelink/plugin.js [hunk 4]
```diff
@@ -9,26 +8,22 @@ CKEDITOR.plugins.add( 'filelink', {
...
-            400,
-            function(){
-            }
-        );
     }
 });
 
 function showDialogPlugin(e){
-    e.openDialog('filelink.dlg');
+    kQuery.magnificPopup.open({
```
Comment (jebbdomingo) [inline resources/assets/ckeditor/plugins/filelink/plugin.js]: @ercanozkaya I replaced the iframedialog plugin with manificPopup, everything is fine except that the Insert `insert-link` event in FILElink still cannot close the modal, same with Cancel `insert-modal-cancel`. `window.parent.SqueezeBox` within FILElink view looks okay but seems to belong to modal other than the one we opened up here.

image

**Comment by ercanozkaya** [comment]
@jebbdomingo We are fixing that as part of https://github.com/joomlatools/fileman/issues/353 so it won't be an issue.

File: resources/assets/ckeditor/plugins/filelink/plugin.js (hunk 4 above)
Comment (ercanozkaya) [reply resources/assets/ckeditor/plugins/filelink/plugin.js]: @jebbdomingo We are fixing that as part of joomlatools/fileman#353 so it won't be an issue.
